version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: boleto-api
    image: boleto-api
    working_dir: /usr/app/boleto-api
    command: npm start
    volumes:
      - ./:/usr/app/boleto-api/
    expose:
      - "3000"
    ports:
      - "3000:3000"
volumes:
  node_modules:
